### ISSUE TITLE
adding Seeders

### ISSUE THREAD

**Issue by HEARC-Miguel-Moreira** [HE-Arc/onlyshop#17]
This will help to test functionalities with some real-looking fake data

**Comment by RuiMarcoLoureiro** [comment]
C'était pas grand chose ton problème avec les seeders.
Enfaite tu remplissais la table Item d'abord. mais Item utilise un id de  l'utilisateur.
Vu que la table utilisateur était pas encore remplie. tu avais le crash.
En gros, il suffisait de mettre dans le bon ordre dans "DataBaseSeeder" les tables à seed (on avait vu dans le workshop un peu le même problème mais avec les migrations)
